name: Run Bun Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun" >> $GITHUB_PATH
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test
